apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmf-cdc
  labels:
    app: tmf-cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmf-cdc
      version: v1
  template:
    metadata:
      labels:
        app: tmf-cdc
        version: v1
    spec:
      containers:
      - name: tmf-cdc
        image: registry.devops.7f8254f4188647b4be19.eastus.aksapp.io/tmf-cdc
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: cm-kafka-cd
        - secretRef:
            name: sc-azure-data
---
apiVersion: v1
kind: Service
metadata:
  name: tmf-cdc
spec:
  selector:
    app: tmf-cdc
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tmf-cdc
spec:
  gateways:
    - default/default
  hosts:
  - tmf-cdc.istio.7f8254f4188647b4be19.eastus.aksapp.io
  http:
  - name: "http-routes"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: tmf-cdc
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tmf-cdc
spec:
  host: tmf-cdc
  subsets:
  - name: v1
    labels:
      version: v1
